global using Aiursoft.DbTools;
global using Aiursoft.EmployeeCenter.Entities;
global using Aiursoft.CSTools.Tools;
global using Microsoft.EntityFrameworkCore;
global using System.Net;
global using System.Text.RegularExpressions;
global using Microsoft.AspNetCore.Identity;
global using System.Security.Claims;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.DependencyInjection;
global using static Aiursoft.WebTools.Extends;
